define([
    "deliteful/Button",
    "xblox/RunScript",
    "delite/Container",
    "delite/register",
    "dojo/_base/kernel",
    "dojo/_base/lang",
    "dojo/_base/declare",
    "dojo/Deferred",
    "dojo/has",
    "xdojo/declare",
    "xdojo/has",
    'dcl/dcl',
    'dcl/advise',
    'dcl/mini',
    'dstore/mainr',
    'xdojo/declare',
    'dstore/Filter',
    'xblox/mainr',

    "xblox/CSSState",
    "xblox/StyleState",
    'xblox/model/html/SetState',
    'xide/mainr',

    'xfile/manager/FileManager',
    'xwire/main',
    'xcf/mainr',
    'xide/utils',
    'xnode/manager/NodeServiceManager',
    'xapp/manager/Application',
    'xapp/manager/Context',
    
    
    'decor/Evented',
    'decor/Invalidating',
    'decor/ObservableArray',
    'decor/features',
    'decor/schedule',
    'decor/sniff',

    'dpointer/events',
    'dpointer/handlers/features',
    'dpointer/handlers/mouse',
    'dpointer/handlers/touch',
    'dpointer/handlers/touchTracker',
    'dpointer/handlers/utils',

    "delite/Template",
    "delite/Widget",
    "delite/handlebars",
    "delite/theme",

    "deliteful/Slider",
    "deliteful/Combobox",
    "deliteful/Select",
    "deliteful/Checkbox",
    "deliteful/RadioButton",
    "deliteful/ToggleButton",
    "deliteful/Switch",
    "deliteful/features",
    "deliteful/ProgressIndicator",
    "deliteful/ViewStack",
    "deliteful/Panel",
    "deliteful/SidePane",
    "deliteful/LinearLayout",
    "deliteful/Button",
    "xdeliteful/Button",
    "deliteful/StarRating",
    "deliteful/ProgressBar",
    "deliteful/list/List",
    "dojo/selector/_loader",
    "xdeliteful/TabBar",
    "xdeliteful/MediaPlayer",
    "deliteful/Accordion",
    "requirejs-domready/domReady"
], function(Button,RunScript,register){
    
});
